server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://192.168.2.201:5433/postgresdev
    username: devusr
    password: d3vusr
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect