# .github/workflows/build-and-push.yml (ใน my-springboot-app repo)
name: Build & Push Spring Boot Docker Image

on:
  push:
    branches:
      - main # หรือ branch ที่คุณใช้พัฒนา
  workflow_dispatch: # อนุญาตให้ Trigger ด้วยมือ

env:
  JAVA_VERSION: '24'
  APP_NAME: 'my-springboot-app' # ชื่อแอปพลิเคชัน (ควรตรงกับชื่อ Docker image ส่วนท้าย)

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # กำหนด Environment Variable สำหรับ Image Tag โดยตรงในระดับ Job
    env:
      IMAGE_TAG: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
    outputs:
      # ยังคง Output เพื่อส่งค่าไปยัง Job อื่นๆ (ถ้ามี)
      image_tag_output: ${{ env.IMAGE_TAG }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven' # Or 'gradle'

      - name: Build Spring Boot application
        run: mvn clean package -DskipTests # Or 'gradlew bootJar'

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAG }} # <-- อ้างอิงถึง Environment Variable ที่กำหนดในระดับ Job
          file: ./Dockerfile
